version: '3'
services:
    web:
        build:
            context: build/docker
            args:
                http_proxy: ${http_proxy}
        ports:
            - "8080:8080"
    vault:
        image: "vault:0.9.5"
        cap_add:
            - IPC_LOCK
        volumes:
            - "./vault/config:/vault/config"
            - "./vault/logs:/vault/logs"
            - "./vault/file:/vault/file"
        command: server