version: '3'
services:
    vault:
        build:
            context: build/docker/vault
        ports:
            - "8200:8200"
        cap_add:
            - IPC_LOCK
        volumes:
            - "vaultlogs:/vault/logs"
            - "vaultfile:/vault/file"
        command: server
    web:
        build:
            context: build/docker/web
            args:
                http_proxy: ${http_proxy}
        ports:
            - "8080:8080"
        depends_on:
          - vault
        environment:
          - SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID

volumes:
  vaultlogs:
  vaultfile:
